### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#116]
Rename the current `RunIndividualFiles` class to something along the lines of `BatchProcessFiles`, and add the option to specify a `batch_size`, to enable batch processing. Then instead of running data files in batches of size 1, as in `RunIndividualFiles`,  run data files in batches of size `batch_size`. `RunIndividualFiles` can simply specify a `batch_size` of 1.

**Comment by jswift-stfc** [comment]
So..  I have a couple of questions regarding this.
Firstly, in a particular experiment, will the number of data files **always** be the same for all samples, or could this vary?
Also, I think it would be good to make use of parallelism here - what do you think? Maybe it can be optional - however, for me it makes sense, since each batch is in isolation of the others.
Furthermore, would it be necessary to run `purge_det` before running `gudrun_dcs` on each batch, or could we run it on the entire input file beforehand?

**Comment by trisyoungs** [comment]
1. Number of data files per sample can (and will) vary, so you'll have to consider this in the design.

2. Doing as much in parallel as possible seems like a good idea - perhaps a a general control to allow specification of the max number of different processes to run at once should be implemented?

3. `purge_det` can be run once at the beginning of any batch / tweak / processing run, although even this is wasteful. Perhaps we should consider better control over when (and over what) the purge is actually run.

**Comment by jswift-stfc** [comment]
Regarding 1 - would it be better to process samples separately in this sense?

**Comment by trisyoungs** [comment]
You may lose efficiency by doing so. Perhaps you need a kind of "dry run" algorithm to determine how many "sample equivalents" need to be run, then partition those samples up and run them as separate input files according to the max number of processes available?
