### ISSUE TITLE
Broader set of tools for iteratively tweaking values

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#117]
Currently, we can only iteratively tweak the `tweak factor`. It would be useful if we could iteratively tweak other values, such as the `density`, `thickness/radius` (depending on geometry) and `composition`. Since these values are not always known.

**Comment by jswift-stfc** [comment]
When we talk about `tweaking` - we are talking about iteratively altering the target value, until we achieve a `DCS level` that we would expect for the given configuration, is that correct?

**Comment by trisyoungs** [comment]
Yes.  All of these different kinds of "tweaking" compare the calculated vs experimental DCS levels, with a view to obtaining 100%.
