### ISSUE TITLE
Attributes that affect purging

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#128]
I am adding a flag to the `GudrunFile` class to determine whether the detectors have been purged or not. However, we must consider that the detectors may be purged, then attributes changed, and it will still look as if it has been purged - although I'm assuming that some of the attributes related to the `GudrunFile` affect the purging process, so it would have to be run again.

As far as I am aware, alterations to the following attributes would require purging again:

- Any configuration/data files, and period numbers.
- Instrument name.
- Spectrum numbers for incident beam monitor.
- Channel numbers for spike analysis and acceptance factor.

Can you confirm that this is correct, and that it would be reasonable to set the flag to `False`, if any of these are changed?

**Comment by trisyoungs** [comment]
That covers most stuff, but there are also some parameters related to the purge that we need to provide editability for.  I don't think we currently have controls for them?  There is a useful additional feature to implement here as well - the ability to include / exclude the Sample and Can datafiles in the purge (the default should be the former).

**Comment by jswift-stfc** [comment]
We have no controls, through the GUI, for purge parameters. We have however functionality to alter the following parameters through our scripts:

- Number of standard deviations above and below the mean ratio.
- Range of "std's" around the mean standard deviation.
- Ignore existing bad spectrum and spike files?

These can be implemented into the GUI. When we say exclude Sample and Container data files, would that mean excluding the Samples and Containers, or just not writing out any data files for them? Are there any other parameters that we need?

**Comment by trisyoungs** [comment]
Excluding their raw/nxs files from being written to purge_det.txt (or whatever the input file gets called) leaving just the normalisation and background data files.
