### ISSUE TITLE
Create iterator class for in-elasticity subtractions

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#22]
A class needs to be created for performing iterations of gudrun_dcs with in-elasticity subtractions.

A suitable name for the class might be `WavelengthSubtractionIterator`.

Some notes on the functionality of the iterator:

- Switch between wavelength and Q scale.
- On wavelength scale, for each sample, always set top hat width to 0, scale to 3 (for wavelength), and the name of file for self scattering to the .mint01 file relevant to the sample.
- On the first iteration on the wavelength scale, turn off subtracting of wavelength-binned data.
- On the Q scale, for each sample, always set the top hat width back to its initial value, scale to 1 (for Q), and the name of file for self scattering to the .msubw01 file relevant to the sample.
- On the first iteration on the Q scale, turn on subtracting of wavelength-binned data - and keep it on for the rest of the iterations.

@trisyoungs could you please confirm if this is OK, and add anything you think I missed?

**Comment by jswift-stfc** [comment]
Also an additional question, for means of clarification - when we run for n iterations, do we perform n iterations on each scale?

**Comment by trisyoungs** [comment]
That looks complete to me.  The only other thing I noticed in my old bash script was that an additional value of `-0.01` was manually-appended to the min, max, stepsize line when performing the wavelength run. I can only assume that this indicates a logarithmic bin width should (must?) be used when binning by wavelength.

**Comment by trisyoungs** [comment]
One iteration comprises a wavelength run followed by a standard Q binning run (`W` | `Q`).  Two iterations would be `W` | `Q` | `W` | `Q`, etc.

**Comment by jswift-stfc** [comment]
> That looks complete to me. The only other thing I noticed in my old bash script was that an additional value of `-0.01` was manually-appended to the min, max, stepsize line when performing the wavelength run. I can only assume that this indicates a logarithmic bin width should (must?) be used when binning by wavelength.

Yes, forgot about that! Thanks for pointing it out.

**Comment by jswift-stfc** [comment]
Should the "runThisSample" attribute that I added be considered when iterating samples?

**Comment by trisyoungs** [comment]
Yes.  I think that we can consider the "runThisSample" to be so generic that it should be respected in all tools / methods / iterations that we add.
