### ISSUE TITLE
Structure factor plotting options

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#227]
Currently we have the option to plot mint01 and mdcs01 files together.  We should split this into separate options for mint01 only, mdcs01 only, or mint01/mdcs01 together.  This option should be available for both individual samples as well as the combined plotting panel.

**Comment by jswift-stfc** [comment]
Should these options look something like this?

`Structure Factor (mint01, mdcs01)`
`Structure Factor (mint01)`
`Structure Factor (mdcs01)`

**Comment by trisyoungs** [comment]
Let's be slightly more explicit and say:
```
Structure Factor (mint01 & mdcs01)
Structure Factor (mint01 only)
Structure Factor (mdcs01 only)
```
