### ISSUE TITLE
Enumerate Top Hat Width options

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#229]
The top hat width in the Fourier transform may take a negative number to represent a slightly different approach.  We should enumerate this to make things clear to the user what it is they are requesting.

**Comment by jswift-stfc** [comment]
Can you expand further on this please? What does the negative/positive represent?

**Comment by trisyoungs** [comment]
A negative value effectively means "calculate the average level from the abs(Q) value provided, and use that in the Top Hat subtraction" while a positive value refers to an absolute width of the Top Hat function. The specifics escape me right now, but I recall it's in one of the Appendices of the Gudrun manual...
