### ISSUE TITLE
Show total sample thickness

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#231]
Add a simple label underneath the upstream / downstream thicknesses of the Sample to calculate and show the total thickness.

**Comment by jswift-stfc** [comment]
Is this just the sum of the upstream and downstream thickness? And also, should we do anything similar for cylindrical samples?

**Comment by trisyoungs** [comment]
Yes - nice and simple.  For cylindrical samples the situation is a little less clear, and I'd probably leave that for now.
