### ISSUE TITLE
Purging with default parameters

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#263]
As a user, when I run Gudrun and haven't performed a purge, we ask what should be done.  If I click on "Run with default parameters", I kinda don't want the processing to stop and inform me of the number of detectors making it through the purge. Rather, I want the Gudrunning to happen!

To cater for the case where this "blind" running of the purge might introduce errors due to bad numbers of detectors, we could elect to only raise a dialog *if* the number of detectors comes outside of our acceptable (per-instrument) boundaries, once that functionality is implemented.

**Comment by jswift-stfc** [comment]
I was just thinking about this! It is rather annoying for it to pop-up after Gudrun has started running. Maybe it is time to visit #140.
