### ISSUE TITLE
Main tab name

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#264]
Tiny issue here, but we should change the title of the `GudPy Input File` tab to something more appropriate. However, quite what that is I don't know!  `Gudrun Input` perhaps?

**Comment by jswift-stfc** [comment]
We should definitely relate it to `Gudrun`, `Gudrun Input` sounds good. We could also have `Gudrun Parameters`?

**Comment by jswift-stfc** [comment]
Closed by 1a30cd60f3de544d87f1a0635ea8e0dc8f0eb9ac.
