### ISSUE TITLE
Selecting packaged data files

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#272]
In a "flat" installation of Gudrun/GudrunGUI the `StartupFiles` folder is readily accessible. In the PyInstaller package it is not.  I noticed for the water data that I'm testing on that I didn't have the normalisation DCS parameters set ("Differential cross section file" on the Normalisation page). However, I can't choose the file I need because the contents of the decompressed tmp file are not accessible.

For PyInstaller artifacts we may have to consider some kind of `LineEdit` / `QComboBox` hybrid, where the former allows any arbitrary file to be selected and the latter provides a list of suitable files contained in the packaged `StartupFiles` directory.

**Comment by jswift-stfc** [comment]
Do you mean that when you click the `Browse` button, you are not directed to the `StartupFiles` directory?

**Comment by trisyoungs** [comment]
That would be a simpler assessment of the problem, yes!

**Comment by jswift-stfc** [comment]
Huh strange, I thought that I had implemented that already! Need to have a check on all platforms to see if it's working.

**Comment by jswift-stfc** [comment]
Closing this for now because I think it is resolved.
