### ISSUE TITLE
Reset zoom should undo any translation?

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#277]
Currently if you translate a plot, and then "reset zoom" it leaves the translation as is, even if you have/haven't zoomed in. I feel like we should rename the context menu option to something like "Reset View" / "Reset Viewport", and have it reset any translation/zooming performed.

**Comment by trisyoungs** [comment]
Agreed.  What we want is an option to reset the plot to its "show all" state.

**Comment by jswift-stfc** [comment]
Closed by #281.
