### ISSUE TITLE
Persistent Components?

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#280]
It would probably be quite useful to be able to have your defined components persist across instances of running GudPy, i.e. if you define some components and close the GUI and then reopen it, they should still be there.

**Comment by trisyoungs** [comment]
There are dangers with this approach, and it might get a bit messy when the GUI's persistent components clash with those in an input file.

I agree that some ability to reuse components would be useful - perhaps a cleaner approach would be to provide an option to load components (and nothing else) in from an existing input file?

**Comment by jswift-stfc** [comment]
Closed by #282.
