### ISSUE TITLE
Add densityUnits attribute

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#30]
There are two possible units - atoms/Angstrom3 and grams/cm3 - for the density (here and elsewhere).  I assume that Gudrun interprets a negative value as one thing and a positive as the other, but again a separate member in GudPy containing the units would be the way to go.

_Originally posted by @trisyoungs in https://github.com/disorderedmaterials/GudPy/pull/27#discussion_r683489964_

Add an additional attribute, to the classes where density is used, for the units of the density (gm/cm^3 or atoms/A^3).

<density in gm/cm**3. If -ve, then it is assumed to be in atoms/A**3>

So, if we read the density and it is negative, we save its absolute value, and we make densityUnits 0, for instance 0 = atoms/A^3. Then when we write it back out, we negate it.

**Comment by jswift-stfc** [comment]
Do we know if this also applies to normalisation/samples? Currently I am assuming that their density is atoms/A^3..

**Comment by trisyoungs** [comment]
Yes.  Safe to assume that, anywhere there's a `density`, there's also an option to specify the units.
