### ISSUE TITLE
Inelasticity correction not working?

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#386]
Iterating GudPy with the inelasiticy correction appears to generate the correct output structure (e.g. directories named after the iterations) but the correction itself does not seem to be subtracted from the data in the plots. May be due to an issue with "Subtract Wavelength Binned Data" not being auto-enabled when running this iterator?

**Comment by jws-1** [comment]
Subtract Wavelength Binned Data is always auto-enabled for this iterator, apart from for the first wavelength iteration - where it is auto-disabled.
