### ISSUE TITLE
Create functional prototype of GudPy GUI

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#40]
**A functional prototype needs to be created of the GudPy GUI.**

The aim of this prototype is **not** necessarily to be aesthetically pleasing / conform to UI standards - the goal is to produce a prototype that can _replicate the functionality of the Java GudrunGUI_ (that has been implemented in GudPy thus far).

The purpose of this prototype is to **provide a base** for the future GUI programming and prototyping.

Visual progress of this prototype will be added to this issue, alongside the development of the prototype.

**Comment by trisyoungs** [comment]
I'm going to be deliberately provocative in my response to this, and I'll raise the following points for discussion:

1) Do we want to emulate the layout and functional components of the original GUI so closely? Would a revolution be better than an evolution?
2) Does the preview of the input file on the right-hand side really need to be there?  It takes up valuable screen real estate, and what is its true purpose? Debugging for the developers? Checking mechanism for users (unlikely!)? I have only ever used it to copy/paste chunks from elsewhere (e.g. sample compositions) that I didn't want to type in again, but new mechanisms to do that from the GUI can easily be introduced.
3) A dynamically-changing column of buttons (or a set of growing vertical tabs in the original) feels like a clumsy re-interpretation of a relatively standard component a QTreeView.  Given that we have defined relationships / ownerships between objects in GudPy, this could be a much better way of representing the data. You could even make the items in the QTreeView checkable, which would control whether they are selected for analysis or not.

**Comment by jswift-stfc** [comment]
> I'm going to be deliberately provocative in my response to this, and I'll raise the following points for discussion:
> 
> 
> 
> 1) Do we want to emulate the layout and functional components of the original GUI so closely? Would a revolution be better than an evolution?
> 
> 2) Does the preview of the input file on the right-hand side really need to be there?  It takes up valuable screen real estate, and what is its true purpose? Debugging for the developers? Checking mechanism for users (unlikely!)? I have only ever used it to copy/paste chunks from elsewhere (e.g. sample compositions) that I didn't want to type in again, but new mechanisms to do that from the GUI can easily be introduced.
> 
> 3) A dynamically-changing column of buttons (or a set of growing vertical tabs in the original) feels like a clumsy re-interpretation of a relatively standard component a QTreeView.  Given that we have defined relationships / ownerships between objects in GudPy, this could be a much better way of representing the data. You could even make the items in the QTreeView checkable, which would control whether they are selected for analysis or not.

1. I don't think we should do that - I think partly the reason I have done is fear of changing things **too** much..
2. I only included it at the moment because one or two of the survey respondents found it useful - maybe it can be something optional, rather than something we force upon the user?
3. I agree with what you say!
