### ISSUE TITLE
Enumerate Instrument Names

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#42]
Instrument names can possibly be enumerated? This will possibly make GUI programming easier - as instrument names will most likely be displayed in a combo box, the value of each member could correspond to an index in the combo box?
`SANDALS = 0
 GEM = 1
 NIMROD = 2
 D4C = 3
 POLARIS = 4
 HIPD = 5
 NPDF = 6`

**Comment by trisyoungs** [comment]
Yes, this would be a sensible and extensible approach.
