### ISSUE TITLE
Enumerate Data File Types

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#43]
Similar to #42, data file types can be enumerated for ease of use.
`RAW = 0 SAV = 1 TXT = 2 NXS = 3 NONE/ALL = 4`

Can't figure out if `*` refers to all types, or none?

**Comment by trisyoungs** [comment]
If we're talking about input neutron data files then it does make sense to have an enumeration for that. I don't think that `TXT`, `SAV`, and `NONE/ALL` fit in to that.  BTW, an asterisk means "no file" - in the new GUI I wouldn't enforce this idiosyncrasy on the user!

**Comment by jswift-stfc** [comment]
> If we're talking about input neutron data files then it does make sense to have an enumeration for that. I don't think that `TXT`, `SAV`, and `NONE/ALL` fit in to that. BTW, an asterisk means "no file" - in the new GUI I wouldn't enforce this idiosyncrasy on the user!

Okay! I assumed that it was suitable, since the above values were the only available options within the current GUI!

**Comment by trisyoungs** [comment]
TBH I'm not sure what the `SAV` files are...

**Comment by jswift-stfc** [comment]
No mention of `SAV` files in the source..

**Comment by jswift-stfc** [comment]
Not implementing.
