### ISSUE TITLE
Standardise Main Menu

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#76]
The main menu should be standardised to use the expected `File` and `Edit` menus, for instance, with the `Run` menu left as-is.  The `Plot` menu can be removed, and the current contents of the `View` menu can be moved to the new `File` menu.

Also, there is no option to "save" or "save as..." input files.

**Comment by jswift-stfc** [comment]
Just for some clarification - what should the `Edit` menu be used for? Is the functionality expected to be the same as that of the Java Gudrun GUI's `Edit` menu?

**Comment by trisyoungs** [comment]
In principle it can contain the same stuff, yes, but feel free to change / reorganise non-standard things if you think they are out-of-place.
