### ISSUE TITLE
Layout of MainWindow

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#77]
The layout of the main window can be improved a little bit.  At present the leftmost `objectTree` has a fixed width of 256 pixels - limiting the size of any widget is generally a bad idea given the variety of screen sizes, resolutions, and accessibility options available over systems.

I would suggest the following:
- Allow the maximal size for the `objectTree` (Qt's idiosyncratic 16777215)
- Set the Horizontal SizePolicy to `Minimum`
- Set the Horizontal SizePolicy of the `objectStack` to `Expanding`

**Comment by jswift-stfc** [comment]
Closed by #87.
