### ISSUE TITLE
Rename tweak factor appropiately

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/GudPy#8]
The 'tweak factor' is not descriptive, and can be renamed. It has been suggested that it is renamed to 'packing fraction'.

**Comment by trisyoungs** [comment]
Need to be careful here to ensure that we don't confuse users bringing in old input files containing tweak factors, and that we convert to/from tweak to packing on i/o.

**Comment by jswift-stfc** [comment]
```
The sample “tweak” factor. (Horrible name!) This is really the reciprocal of the
packing fraction: a packing fraction of 0.5 would translate to a tweak factor of 2, and
so on.
```
From the Gudrun manual.
