### ISSUE TITLE
Modification Status / Filename

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#91]
Nice to show the current input filename and its modification status in the main window titlebar. This of course would involve monitoring every control which is able to modify the data in `GudrunFile`, which is a bit of a pain, but you already have the signals from those widgets, so perhaps simply having a `setAsModified()` function to adjust the titlebar and set a flag would be enough.

**Comment by jswift-stfc** [comment]
Closed by #100.
